version: '3.9'
services:
  biddy-db:
    image: postgres
    container_name: biddy_container
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: biddy_password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres  
  
volumes:
  postgres:
